// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidExtensionPackageString = "85c4ed75-3e80-4378-9884-b3f5ba1416ea";
        public static Guid guidExtensionPackage = new Guid(guidExtensionPackageString);

        public const string guidExtensionPackageCmdSetString = "bdc1a0e4-6fde-4979-91cb-e2f608d6cdbd";
        public static Guid guidExtensionPackageCmdSet = new Guid(guidExtensionPackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
    }
}
